server:
  port: 8080
spring:
  datasource:
    driver-class-name: ${reservoir.datasource.driver-class-name}
    url: jdbc:mysql://${reservoir.datasource.host}:${reservoir.datasource.port}/${reservoir.datasource.database}?serverTimezone=UTC
    username: ${reservoir.datasource.username}
    password: ${reservoir.datasource.password}


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

token:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: userSKey
    # 设置jwt签名加密时使用的秘钥
    user-ttl: 600000 # 10分钟
    # 设置jwt签名加密时使用的秘钥
    user-token-name: userToken